FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем код приложения
COPY . /app/

ENV PYTHONPATH="${PYTHONPATH}:/app"

# Запуск приложения
CMD ["pytest", "-v", "./tests/test_db_operations.py"]
