pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ViktoriiaLesykk/aqa_090125', branch: 'homework_31'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pytest
                '''
            }
        }
        

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest aqa_090125/lesson_31/homework_31/test_calculator.py'
                '''
            }
        }
    }
}