import requests
"""
Написати 25 XPath та 25 CSS локаторів для сайту https://qauto2.forstudy.space/
"""

username = "guest"
passwd = "welcome2qauto"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

ebutton_1 = "//div[]"

# XPath Локатори
hillel_auto_logo = "//a[@class='header_logo']//*[@xmlns='http://www.w3.org/2000/svg']"
header_text = "//h1[@class='hero-descriptor_title display-2' and text()='Do more!']"
text_under_header = "//p[@class='hero-descriptor_descr lead' and text()='With the help of the Hillel auto project, you will have the opportunity to get hands-on experience in manual testing.']"
sign_in_button = "//*[@class='header_right d-flex align-items-center']//*[text()='Sign In']"
email_field_in_login_form = "//input[@id='signinEmail']"
password_field_in_login_form = "//input[@id='signinPassword']"
registration_bttn = "//*[@text()='Registration']"
login_bttn = "//*[@text()='Login']"
name_input_in_registration_form = "//div[@class='form-group']//input[@id='signupName']"
last_name_input_in_registration_form = "//div[@class='form-group']//input[@id='signupLastName']"
email_input_in_registration_form = "//div[@class='form-group']//input[@id='signupEmail']"
password_input_in_registration_form = "//*[@id='signupPassword']"
re_enter_password_in_registration_form = "//*[@type='password']//following::input[1]"
guest_login_button = "//button[text()='Guest log in']"
garage_button = "//nav[@class='header_nav']//a[text()='Garage']"
add_a_car_button = "//button[text()='Add car']"
brand_dropdown = "//select[@id='addCarBrand']"
first_brand_option = "//select[@id='addCarBrand']//option[1]"
third_model_option = "//select[@id='addCarModel']//option[3]"
mileage_input_field = "//input[@id='addCarMileage']"
fuel_expenses_button = "//button[contains(text(),'Fuel expenses')]"
fuel_expenses_page_title = "//div[@class='panel-page_heading']//h1[contains(text(),'Fuel expenses')]"
add_an_expense_button = "//button[contains(text(),'Add an expense')]"
liters_input_field = "//input[@id='addExpenseLiters']"
total_cost_input_field = "//input[@id='addExpenseTotalCost']"
add_button_in_expense_form = "//button[text()='Add']"
cancel_button_in_expense_form = "//button[text()='Cancel']"

# CSS Локатори
hillel_auto_logo_css = "a.header_logo svg"
header_text_css = "h1.hero-descriptor_title.display-2"
text_under_header_css = "p.hero-descriptor_descr.lead"
sign_in_button_css = ".header_right button:nth-child(1)"
email_field_in_login_form_css = "#signinEmail"
password_field_in_login_form_css = "#signinPassword"
registration_button_css = ".modal-footer .btn-registration"
login_button_css = ".modal-footer .btn-login"
name_input_in_registration_form_css = ".form-group #signupName"
last_name_input_in_registration_form_css = ".form-group #signupLastName"
email_input_in_registration_form_css = ".form-group #signupEmail"
password_input_in_registration_form_css = "#signupPassword"
re_enter_password_in_registration_form_css = ".form-group input[type='password']:nth-child(2)"
guest_login_button_css = ".form-group button.btn-guest-login"
garage_button_css = "nav.header_nav a[href='/garage']"
add_a_car_button_css = "button#addCarBtn"
brand_dropdown_css = "select#addCarBrand"
first_brand_option_css = "select#addCarBrand option:first-child"
third_model_option_css = "select#addCarModel option:nth-child(3)"
mileage_input_field_css = "input#addCarMileage"
fuel_expenses_button_css = ".header_nav a[href='/fuel']"
fuel_expenses_page_title_css = ".panel-page_heading h1.page-title-fuel"
add_an_expense_button_css = ".btn-expenses-add"
liters_input_field_css = "input#addExpenseLiters"
total_cost_input_field_css = "input#addExpenseTotalCost"
add_button_in_expense_form_css = ".modal-footer .btn-add"
cancel_button_in_expense_form_css = ".modal-footer .btn-cancel"
