import requests
"""
Написати 25 XPath та 25 CSS локаторів для сайту https://qauto2.forstudy.space/
"""

username = "guest"
passwd = "welcome2qauto"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

hillel_auto_logo = "//a[@class='header_logo']//*[@xmlns='http://www.w3.org/2000/svg']"
sign_in_button = "//*[@class='header_right d-flex align-items-center']//*[text()='Sign In']"
email_field_in_login_form = "//div[@class='form-group']//input[@id='signinEmail']"
password_field_in_login_form = "//div[@class='form-group']//input[@id='signinPassword']"
registration_bttn = "//*[@class='modal-footer d-flex justify-content-between']//*[text()='Registration']"
login_bttn = "//*[@class='modal-footer d-flex justify-content-between']//*[text()='Login']"
forgot_password_bttn = "//div[@class='modal-content']//*[text()='Registration']"
sign_up_bttn = "//*[contains(text(),'Sign up')]"
name_input_in_registration_form = "//div[@class='form-group']//input[@id='signupName']"
last_name_input_in_registration_form = "//div[@class='form-group']//input[@id='signupLastName']"
email_input_in_registration_form = "//div[@class='form-group']//input[@id='signupEmail']"
password_input_in_registration_form = "//div[@class='form-group']//input[@id='signupPassword']"
re_enter_password_in_registration_form = "//*[@type='password']//following::input[1]"
guest_login = "//*[@class='header_right d-flex align-items-center']//*[text()='Guest log in']"
my_profile_in_guest_login_page = "//*[contains(text(), 'My profile')]"
garage_in_my_profile_dropdown = "//nav[@class='user-nav_menu dropdown-menu show']//*[text()='Garage']"
fuel_expenses_in_my_profile_dropdown = "//nav[@class='user-nav_menu dropdown-menu show']//*[text()='Fuel expenses']"
instructions_in_my_profile_dropdown = "//nav[@class='user-nav_menu dropdown-menu show']//*[text()='Instructions']"
logout_in_my_profile_dropdown = "//nav[@class='user-nav_menu dropdown-menu show']//*[text()='Logout']"
garage_page_title = "//div[@class='panel-page_heading d-flex justify-content-between']//h1[1]"
add_a_car_bttn = "//*[@class='panel-page_heading d-flex justify-content-between']//button[text()='Add car']"
add_a_car_form_name = "//select[@id='addCarBrand']"
brand_car_dropdown_1 = "//select[@id='addCarBrand']//option[1]"
brand_car_dropdown_2 = "//select[@id='addCarBrand']//option[2]"
brand_car_dropdown_3 = "//select[@id='addCarBrand']//option[3]"
brand_car_dropdown_4 = "//select[@id='addCarBrand']//option[4]"
brand_car_dropdown_5 = "//select[@id='addCarBrand']//option[5]"
car_model_dropdown_1 = "//select[@id='addCarModel']//option[1]"
car_model_dropdown_2 = "//select[@id='addCarModel']//option[2]"
car_model_dropdown_3 = "//select[@id='addCarModel']//option[3]"
car_model_dropdown_4 = "//select[@id='addCarModel']//option[4]"
car_model_dropdown_5 = "//select[@id='addCarModel']//option[5]"
mileage_input = "//div[@class='input-group']//input[@id='addCarMileage']"
add_bttn_in_add_a_car_form = "//div[@class='modal-footer d-flex justify-content-end']//*[text()='Add']"
cancel_bttn_in_add_a_car_form = "//div[@class='modal-footer d-flex justify-content-end']//*[text()='Cancel']"
fuel_expenses_bttn = "//nav[@class='header_nav d-flex align-items-center']//a[text()='Fuel expenses']"
fuel_expenses_page_title = "//div[@class='panel-page_heading d-flex flex-column flex-lg-row']//h1[text()='Fuel expenses']"
add_an_expense_bttn = "//*[contains(text(),'Add an expense')]"
vehicle_dropdown_1 = "//select[@name='carId' and @id='addExpenseCar']//option[1]"
vehicle_dropdown_2 = "//select[@name='carId' and @id='addExpenseCar']//option[2]"
report_date_input = "//div[@class='form-group']//div[@class='input-group']//input[@id='addExpenseDate']"
number_of_liters_input = "//div[@class='form-group']//div[@class='input-group']//input[@id='addExpenseLiters']"
total_cost_input = "//div[@class='form-group']//div[@class='input-group']//input[@id='addExpenseTotalCost']"
add_bttn_in_add_expense_form = "//div[@class='modal-footer d-flex justify-content-end']//button[contains(text(), 'Add')]"
cancel_bttn_in_add_expense_form ="//div[@class='modal-footer d-flex justify-content-end']//button[contains(text(), 'Cancel')]"
instructions_bttn = "//nav[@class = 'header_nav d-flex align-items-center']//a[contains(text(), 'Instructions')]"
search_bttn_in_instructions_page = "//button[@class='instructions-search-controls_search btn btn-primary' and (text()='Search')]"
brand_car_dropdown_in_instructions = "//div[@class='instructions-search-controls_item brand-select-dropdown dropdown']//button[@id='brandSelectDropdown']"
car_model_dropdown_in_instructions = "//div[@class='instructions-search-controls_item model-select-dropdown dropdown']//button[@id='modelSelectDropdown']"
hillel_auto_clickable_logo_footer = "//a[@class='footer_logo']//*[@xmlns='http://www.w3.org/2000/svg']"


